### ISSUE TITLE
当它的数量超过demo中的值不再显示，有什么更好的解决方案吗？

### ISSUE THREAD

**Issue by git-cncoder** [xiaohaibin/CustomWaterView#1]
当它的数量超过demo中的值不再显示，有什么更好的解决方案吗？
```
private void addWaterView(List<WaterModel> modelList) {
        int[] xRandom = randomCommon(1, 8, modelList.size());
        int[] yRandom = randomCommon(1, 7, modelList.size());
}
```

**Comment by xiaohaibin** [comment]
屏幕能展示的数量肯定是有限的，支付宝也是同样处理，要么写死每个水滴的位置，要么通过算法计算出每个水滴的位置，动态分布

**Comment by git-cncoder** [comment]
嗯嗯，好的。尝试扩展下，支付宝森林能量多会叠加显示。目前我的父布局足够大可以再多放一些。如下
![image](https://user-images.githubusercontent.com/22268505/42994461-baf88042-8c40-11e8-91c2-3a3bc4654751.png)

**Comment by xiaohaibin** [comment]
嗯，可以
